### ISSUE TITLE
rtmp2sink element is not installed

### ISSUE THREAD

**Issue by gke96** [edumeet/edumeet-recorder#12]
### Describe your issue
The gstreamer version installed via apt-get is 1.16 however rtmp2 was introduced in 1.18

Stream or Both modes do not work due to rtmp2sink element not existing.

#### Expected Behavior
Installation of a gstreamer version with rtmp2 plugin in installation script.

#### Observed Behavior
![image](https://user-images.githubusercontent.com/11146551/153724917-e8497a8e-23f9-4013-8c95-8a4545492919.png)

#### Setup
- **Operating System:**
Ubuntu 20.04 and ubuntu20.04 on WSL2 (two different devices, same results)
- **Device:** Computer /  Virtual Machine
- **Docker Version:**
![image](https://user-images.githubusercontent.com/11146551/153725155-3b48ad50-feb7-40c0-b0da-6b78874222bc.png)

### How reproducible is the bug?
Very.
Just do default installation and start a stream.

### Solutions you have tried

I have tried using rtmp (rtmp1) instead in pipeline. However it is a very problematic plugin. 'stream' mode "somewhat" works but 'both' mode does not.

**Comment by gke96** [comment]
Currently solved by using ubuntu21.04 for dockerfile instead. (ubuntu21.04 has gstreamer1.18 by default)
I have made a few more changes so that it compiles on ubuntu21.04 without linker errors.

**Comment by hevc** [comment]
Test current develop. Please reopen if needed.
