### ISSUE TITLE
Not able to start recording session

### ISSUE THREAD

**Issue by harshad-98** [edumeet/edumeet-recorder#15]
I have followed the steps mentioned in the readme file to run edumeet recorder.
`
- git clone https://github.com/edumeet/edumeet-recorder.git
- cd edumeet-recorder
- docker build -t edumeet-recorder . (few minutes to half an hour building)
- docker run -v /tmp:/records --rm -it --network=host edumeet-recorder
`
after which i joined the session at https://letsmeet.no/

and ran the curl command to start recording the session.

The recorded session has a few seconds of the blank screen followed by the join screen of https://letsmeet.no, Please check the below-attached video of the recording. 

https://user-images.githubusercontent.com/79514170/192447716-88a41bc0-d47e-449f-9a07-ea743f34de52.mp4

**Comment by hevc** [comment]
Hi,
I repeated your steps. The recorder has worked properly.   

Test it on an official edumeet instance. Try:  
`curl -i -H "Accept: application/json" -H "Content-Type: application/json" --data '{"type":"uri", "data":{"bitrate":6000,"uri":"https://letsmeet.no/test-edumeet-recorder?headless=true&displayName=recorder", "stream_uri":"","mode":"record"}}' -X POST http://127.0.0.1:34568/api/start`

Note that the `headless=true` parameter is mandatory for edumeet to avoid welcome screen.

https://user-images.githubusercontent.com/20162255/192467852-dc6dbc09-a710-4422-a947-8d2a9b952a0a.mp4
