### ISSUE TITLE
Query: how to use this with edumeet conference recording?

### ISSUE THREAD

**Issue by dharmeshmaniar** [edumeet/edumeet-recorder#4]
Hi,

Can you please help in understanding how to use this with edumeet conference recording?

**Comment by hevc** [comment]
docker build -t edumeet-recorder .  
docker run -v /tmp:/records --rm --network=host edumeet-recorder  

curl -i -H "Accept: application/json" -H "Content-Type: application/json" --data '{"type":"uri", "data":{"encoder":"h264","bitrate":6000,"uri":"https://letsmeet.no/roomname?headless=true&displayName=recorder","stream_uri":"","mode":"record"}}' -X POST http://127.0.0.1:34568/api/start  

curl -i -H "Accept: application/json" -H "Content-Type: application/json" --data '{"id":1}' -X POST http://127.0.0.1:34568/api/stop

**Comment by Alex-YddeR** [comment]
Building get stucks with 100 Percent CPU usage even we use good machine

**Comment by so010** [comment]
This vil need several hours to build.

**Comment by hevc** [comment]
If you have a lot of ram, you can increase the number of build threads in line 49: https://github.com/edumeet/edumeet-recorder/blob/develop/scripts/install.sh

**Comment by Alex-YddeR** [comment]
Recording 1 session with 2 users in a 16 core machine uses almost 30 percent of CPU. is there a way to reduce the CPU Performance.

**Comment by hevc** [comment]
Processing on the CPU was done for the reason that there is usually no GPU
on the servers.

Yes, there is a possibility to reduce the CPU. The graphics card context
should be passed to the docker and the line
https://github.com/edumeet/edumeet-recorder/blob/ad9508db06f6fc6ed4fefec94be4f64396a54973/src/Common/Recorder/UriRecorder.cpp#L29
should be without "video/x-raw,framerate=30/1 !". The "x-raw" means processing
on the CPU. Then the wpe webkit will use opengl to render the image to
encode.


wt., 21 wrz 2021 o 14:04 Alex-YddeR ***@***.***> napisał(a):

**Comment by Alex-YddeR** [comment]
So i would need a CPU with integrated graphics here.

Can we record multiple sessions at the same time? as i have checked i have started 2 sessions and now when trying to stop the sessions its not working.

Also how to stop the 1 single recording when there are multiple recordings happening.

**Comment by hevc** [comment]
Yes you can start as many sessions as you want.
Example:

Session 1:

curl -i -H "Accept: application/json" -H "Content-Type: application/json"
--data '{"type":"uri", "data":{"encoder":"h264","bitrate":6000,"uri":"
https://letsmeet.no/roomname?headless=true&displayName=recorder","stream_uri":"","mode":"record"}}'
-X POST http://127.0.0.1:34568/api/start
HTTP/1.1 200 OK
Content-Length: 20
Content-Type: application/json

{"status":"started"}

Session 2:

curl -i -H "Accept: application/json" -H "Content-Type: application/json"
--data '{"type":"uri", "data":{"encoder":"h264","bitrate":6000,"uri":"
https://letsmeet.no/roomname?headless=true&displayName=recorder","stream_uri":"","mode":"record"}}'
-X POST http://127.0.0.1:34568/api/start
HTTP/1.1 200 OK
Content-Length: 20
Content-Type: application/json

{"status":"started"}

Status:

url -i -H "Accept: application/json" -H "Content-Type: application/json" -X
GET http://127.0.0.1:34568/api/status
HTTP/1.1 200 OK
Content-Length: 75
Content-Type: application/json

[{"id":1,"records":[],"running":true},{"id":2,"records":[],"running":true}]

Stop:

curl -i -H "Accept: application/json" -H "Content-Type: application/json"
--data '{"id":*1*}' -X POST http://127.0.0.1:34568/api/stop
HTTP/1.1 200 OK
Content-Length: 20
Content-Type: application/json

{"status":"stopped"}

Status:

curl -i -H "Accept: application/json" -H "Content-Type: application/json"
-X GET http://127.0.0.1:34568/api/status
HTTP/1.1 200 OK
Content-Length: 109
Content-Type: application/json

[{"id":*1*,"records":["/records/2021-09-22_07:56:00__0"],"running":*false*
},{"id":2,"records":[],"running":true}]

Stop 2:

curl -i -H "Accept: application/json" -H "Content-Type: application/json"
--data '{"id":*2*}' -X POST http://127.0.0.1:34568/api/stop
HTTP/1.1 200 OK
Content-Length: 20
Content-Type: application/json

{"status":"stopped"}

Status 2 :

 http://127.0.0.1:34568/api/status
HTTP/1.1 200 OK
Content-Length: 143
Content-Type: application/json

[{"id":1,"records":["/records/2021-09-22_07:56:00__0"],"running":*false*
},{"id":2,"records":["/records/2021-09-22_07:57:58__1"],"running":*false*}]

wt., 21 wrz 2021 o 14:46 Alex-YddeR ***@***.***> napisał(a):

**Comment by Alex-YddeR** [comment]
Thanks so much for the steps.
As above process is taking so much CPU usage, how can we record all the RTP streams of the edumeet instead of the screen

Thanks
