### ISSUE TITLE
Unable to start recording [Critical]

### ISSUE THREAD

**Issue by ktahatastan** [edumeet/edumeet-recorder#6]
The commands used to start recording among the "curl" commands return the following response. I've never been able to start recording.

{"error":"Unable to start recording. Missing or wrong parameters"}

**Comment by ktahatastan** [comment]
edit: 

curl -i -H "Accept: application/json" -H "Content-Type: application/json" --data '{"type":"uri", "data":{"encoder":"h264","bitrate":6000,"uri":"https://videojs.github.io/autoplay-tests/plain/attr/autoplay.html","stream_uri":"rtmp://x.rtmp.youtube.com/live2/my-youtube-key","mode":"record"}}' -X POST http://127.0.0.1:34568/api/start


curl -i -H "Accept: application/json" -H "Content-Type: application/json" --data '{"type":"uri", "data":{"encoder":"h264","bitrate":6000,"uri":"https://vjs.zencdn.net/v/oceans.mp4","stream_uri":"rtmp://x.rtmp.youtube.com/live2/my-youtube-key","mode":"record"}}' -X POST http://127.0.0.1:34568/api/start

both of these requests returns 
500 internal server error with errors


127:04:07.629716773    11 0x7f255004db00 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:467:gst_element_factory_make: no such element factory "wpesrc"!
127:04:07.629760791    11 0x7f255004db00 ERROR           GST_PIPELINE subprojects/gstreamer/gst/parse/grammar.y:857:priv_gst_parse_yyparse: no element "wpesrc"
127:04:07.629894401    11 0x7f255004db00 ERROR           GST_PIPELINE subprojects/gstreamer/gst/parse/grammar.y:945:priv_gst_parse_yyparse: link has no source [sink=@0x7f257400e190]
Pipeline failed. Exception: Cannot init pipeline

**Comment by hevc** [comment]
no element "wpesrc" message means that Webkit wpe did not build properly inside docker. Please make sure you have enough RAM. Webkit require huge amounts of RAM during build. You can reduce RAM usage during build here: https://github.com/edumeet/edumeet-recorder/blob/develop/scripts/install.sh#L49. Change ninja -j6 to lower value.

**Comment by hevc** [comment]
Use https://github.com/edumeet/edumeet-recorder/tree/cef to reduce build time, and save CPU usage.
